CREATE TABLE IF NOT EXISTS items_compra (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  cantidad INTEGER NOT NULL DEFAULT 1,
  comprado BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);